### ISSUE TITLE
Add feature to disable or add name patterns

### ISSUE THREAD

**Issue by HonzaSTECH** [TravinDreek/NicknameGenerator#1]
Great app dude, really helped me out, but some of the name patterns repeat too often (such as "xX...Xx" or "MC_...") and it doesn't look very _natural._

I would suggest adding an input field, where users could
- disable certain patterns
- add their own
- set percentual chance for each of them

**Comment by TravinDreek** [comment]
I'll try to add an input field where custom patterns can be set. For chance settings, I don't think it's necessary to be added. All in all, thanks for your suggestions.
